<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Ecalendar extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
    }

    function index()
    {
        $data['_view'] = 'ecalendar/2024/home.php';
        $this->load->view('layouts/main_ecalendar', $data);
    }

    function januari_februari()
    {
        $data['_view'] = 'ecalendar/2024/januari_februari.php';
        $this->load->view('layouts/main_ecalendar', $data);
    }

    function maret_april()
    {
        $data['_view'] = 'ecalendar/2024/maret_april.php';
        $this->load->view('layouts/main_ecalendar', $data);
    }

    function mei_juni()
    {
        $data['_view'] = 'ecalendar/2024/mei_juni.php';
        $this->load->view('layouts/main_ecalendar', $data);
    }

    function juli_agustus()
    {
        $data['_view'] = 'ecalendar/2024/juli_agustus.php';
        $this->load->view('layouts/main_ecalendar', $data);
    }

    function september_oktober()
    {
        $data['_view'] = 'ecalendar/2024/september_oktober.php';
        $this->load->view('layouts/main_ecalendar', $data);
    }

    function november_desember()
    {
        $data['_view'] = 'ecalendar/2024/november_desember.php';
        $this->load->view('layouts/main_ecalendar', $data);
    }
}
