<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Kontak extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        // $this->load->model('Paket_model');
    }

    /*
     * Listing of artikel
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('kontak/index?');
        // $config['total_rows'] = $this->Artikel_model->get_all_artikel_count();
        $this->pagination->initialize($config);

        $user_level = $this->session->userdata('user_level');
        $user_id = $this->session->userdata('user_id');

        // echo '<pre>';
        // print_r($data['artikel']);
        // exit();

        $data['_view'] = 'kontak/index';
        $this->load->view('layouts/main', $data);
    }
}
