<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Landing extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Paket_model');
    }

    function index()
    {
        $data['paket'] = $this->Paket_model->get_all_paket();
        $data['galeri'] = $this->Paket_model->get_all_galeri();
        $data['artikel'] = $this->Paket_model->get_all_artikel();

        $data['_view'] = 'landing';
        $this->load->view('layouts/main', $data);
    }

    function detail_paket($id_paket)
    {
        // Mengambil data paket dari model (sesuaikan dengan implementasi Anda)
        $data['detail_paket'] = $this->Paket_model->get_paket($id_paket);

        // Memuat halaman detail paket
        $data['_view'] = 'paket/detail_paket.php';
        $this->load->view('layouts/main', $data);
    }
}
