<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Paket extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Paket_model');
    }

    /*
     * Listing of paket
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $data['paket'] = $this->Paket_model->get_all_paket($params);


        // echo '<pre>';
        // print_r($data['paket']);
        // exit();

        $data['_view'] = 'paket/index';
        $this->load->view('layouts/main', $data);
    }


    function detail_paket($id_paket)
    {
        $data['paket'] = $this->Paket_model->get_tanggal_keberangkatan_for_detail($id_paket);
        $data['record'] = $this->Paket_model->get_record_with_this_paket($id_paket);
        $data['paketlain'] = $this->Paket_model->get_all_paket();
        // echo '<pre>';
        // print_r($data['record']);
        // exit();
        $data['_view'] = 'paket/detail_paket';
        $this->load->view('layouts/main', $data);
    }

    function umroh()
    {
        $data['paketumroh'] = $this->Paket_model->get_paket_umroh_only();
        $data['_view'] = 'paket/umroh';
        $this->load->view('layouts/main', $data);
    }
    function wisatahalal()
    {
        $data['pakettour'] = $this->Paket_model->get_paket_tour_only();
        // echo '<pre>';
        // print_r($data['paketumroh']);
        // exit();
        $data['_view'] = 'paket/tour';
        $this->load->view('layouts/main', $data);
    }
}
