<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Paket extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Paket_model');
    }

    /*
     * Listing of paket
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $data['paket'] = $this->Paket_model->get_all_paket($params);


        // echo '<pre>';
        // print_r($data['paket']);
        // exit();

        $data['_view'] = 'paket/index';
        $this->load->view('layouts/main', $data);
    }


    function detail_paket($id_paket)
    {
        $data['paket'] = $this->Paket_model->get_tanggal_keberangkatan_for_detail($id_paket);
        $data['record'] = $this->Paket_model->get_record_with_this_paket($id_paket);
        $data['paketlain'] = $this->Paket_model->get_all_paket();
        // echo '<pre>';
        // print_r($data['record']);
        // exit();
        $data['_view'] = 'paket/detail_paket';
        $this->load->view('layouts/main', $data);
    }

    function umroh()
    {
        $data['paketumroh'] = $this->Paket_model->get_paket_umroh_only();
        $data['_view'] = 'paket/umroh';
        $this->load->view('layouts/main', $data);
    }
    function haji()
    {
        // $data['paketumroh'] = $this->Paket_model->get_paket_umroh_only();
        $data['_view'] = 'paket/haji';
        $data['galeri'] = $this->Paket_model->get_all_galeri();
        $this->load->view('layouts/main', $data);
    }
    function wisatahalal()
    {
        $data['pakettour'] = $this->Paket_model->get_paket_tour_only();
        // echo '<pre>';
        // print_r($data['paketumroh']);
        // exit();
        $data['_view'] = 'paket/tour';
        $this->load->view('layouts/main', $data);
    }

    function get_paket()
    {
        // Panggil fungsi get_all_paket dari model
        $paket = $this->Paket_model->get_all_paket_api();

        // Set header response sebagai JSON
        $this->output
            ->set_content_type('application/json')
            ->set_output($paket);
    }

    function get_detail_paket($id_paket)
    {
        // Assuming you have loaded the necessary database library in your CodeIgniter application
        $this->load->database();

        // Assuming 'paket' is the name of your database table
        $this->db->select('*');
        $this->db->from('paket');
        $this->db->where('paket.id_paket', $id_paket);
        $this->db->join('keberangkatan', 'keberangkatan.id_keberangkatan = paket.fk_id_keberangkatan', 'left');

        // Perform the query
        $result = $this->db->get()->row_array();

        // Check if the result is not empty
        if (!empty($result)) {
            // Convert the result to JSON
            $jsonResult = json_encode($result);

            // Return the JSON response
            $this->output
                ->set_content_type('application/json')
                ->set_output($jsonResult);
        } else {
            // Return an empty response or handle the case where the paket with the given ID is not found
            $this->output
                ->set_content_type('application/json')
                ->set_output(json_encode(array('error' => 'Paket not found')));
        }
    }
}
