<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Users_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get petani by id_petani
     */
    function get_users($user_id)
    {
        return $this->db->get_where('tbl_users', array('user_id' => $user_id))->row_array();
    }

    function get_users_by_created_by($user_id)
    {
        return $this->db->get_where('tbl_users', array('created_by' => $user_id))->row_array();
    }

    /*
     * Get all users count
     */
    function get_all_users_count()
    {
        $this->db->from('tbl_users');
        return $this->db->count_all_results();
    }

    /*
     * Get all users
     */
    function get_all_users($params = array())
    {
        $this->db->order_by('user_id', 'asc');
        if (isset($params) && !empty($params)) {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_users')->result_array();
    }

    /*
     * function to add new users
     */
    function add_users($params)
    {
        $this->db->insert('petani', $params);
        return $this->db->insert_id();
    }

    function update_users_dari_petani($user_id, $params)
    {
        $this->db->where('user_id', $user_id);
        return $this->db->update('tbl_users', $params);
    }


    /*
    * function to update users
    */
    function update_users($user_id, $params)
    {
        $this->db->where('user_id', $user_id);
        return $this->db->update('tbl_users', $params);
    }

    /*
    * function to delete users
     */
    function delete_users($user_id)
    {
        return $this->db->delete('tbl_users', array('user_id' => $user_id));
    }

    function register($params)
    {
        $this->db->insert('tbl_users', $params);
        return $this->db->insert_id();
    }
    function update_is_users($id_jamaah, $is_user)
    {
        $this->db->where('id_jamaah', $id_jamaah);
        return $this->db->update('jamaah', $is_user);
    }
}
