<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Ecalendar extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
    }

    function index()
    {
        $data['_view'] = 'ecalendar/2025/index.php';
        $this->load->view('layouts/main_ecalendar', $data);
    }
}
