<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Scan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_kehadiran($id_kehadiran)
    {
        return $this->db->get_where('kehadiran', array('id_kehadiran' => $id_kehadiran))->row_array();
    }

    function get_jamaah($nik)
    {
        $this->db->order_by('jamaah.id_jamaah', 'asc');
        return $this->db->get_where('jamaah', array('nik' => $nik))->row_array();
    }

    function get_jamaah_by_id($id_jamaah)
    {
        $this->db->order_by('jamaah.id_jamaah', 'asc');
        return $this->db->get_where('jamaah', array('id_jamaah' => $id_jamaah))->row_array();
    }

    public function absen_masuk($data)
    {
        return $this->db->insert('presensi', $data);
    }

    public function cek_kehadiran($id_jamaah, $tgl)
    {
        $query_str =
            $this->db->where('id_jamaah', $id_jamaah)
            ->where('tgl', $tgl)->get('presensi');
        if ($query_str->num_rows() > 0) {
            return $query_str->row();
        } else {
            return false;
        }
    }

    public function cek_nik($nik)
    {
        $query_str =
            $this->db->where('nik', $nik)
            ->get('jamaah');
        if ($query_str->num_rows() > 0) {
            return $query_str->row();
        } else {
            return false;
        }
    }

    public function absen_pulang($id_jamaah, $data)
    {
        $tgl = date('Y-m-d');
        return $this->db->where('id_jamaah', $id_jamaah)
            ->where('tgl', $tgl)
            ->update('presensi', $data);
    }
    function add_scan($params)
    {
        $this->db->insert('kehadiran', $params);
        return $this->db->insert_id();
    }

    function update_scan($result_code, $params)
    {
        $this->db->where('nik', $result_code);
        return $this->db->update('jamaah', $params);
    }

    function get_kehadiran_with_jamaah()
    {
        $this->db->join('jamaah', 'kehadiran.id_jamaah=jamaah.id_jamaah', 'left');
        return $this->db->get('kehadiran')->result_array();
    }

    function delete_kehadiran($id_kehadiran)
    {
        return $this->db->delete('kehadiran', array('id_kehadiran' => $id_kehadiran));
    }
}
