<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Paket_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get luasan by id_luasan
     */
    function get_paket($id_paket)
    {
        return $this->db->get_where('paket', array('id_paket' => $id_paket))->row_array();
    }

    /*
     * Get all paket
     */
    function get_all_paket($params = array())
    {
        $this->db->order_by('paket.id_paket', 'desc');
        $this->db->join('tbl_users', 'tbl_users.user_id=paket.created_by', 'left');
        $this->db->join('keberangkatan', 'keberangkatan.id_keberangkatan=paket.fk_id_keberangkatan', 'left');
        $this->db->where('paket.publish', 1);
        return $this->db->get('paket')->result_array();
    }

    function get_tanggal_keberangkatan()
    {
        $this->db->where('is_aktif', '1'); // Tambahkan kondisi is_aktif = 1
        $this->db->order_by('keberangkatan.id_keberangkatan', 'desc');
        return $this->db->get('keberangkatan')->result_array();
    }

    function get_tanggal_keberangkatan_for_detail($id_paket)
    {
        $this->db->join('keberangkatan', 'keberangkatan.id_keberangkatan=paket.fk_id_keberangkatan', 'left');
        $this->db->where('id_paket', $id_paket);
        return $this->db->get('paket')->result_array();
    }

    function get_record_with_this_paket($id_paket)
    {
        $this->db->join('jamaah', 'jamaah.id_jamaah=record_keberangkatan.id_jamaah', 'left');
        $this->db->where('record_keberangkatan.id_paket', $id_paket);
        return $this->db->get('record_keberangkatan')->result_array();
    }







    function get_all_galeri($params = array())
    {
        $this->db->order_by('img_dropzone.id', 'desc');
        if (isset($params) && !empty($params)) {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('img_dropzone')->result_array();
    }

    function get_all_artikel($params = array())
    {
        $this->db->order_by('artikel.id_artikel', 'desc');
        return $this->db->get('artikel')->result_array();
    }

    function get_artikel($id)
    {
        return $this->db->get_where('artikel', array('id_artikel' => $id))->row_array();
    }
}
