<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Paket_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get luasan by id_luasan
     */
    function get_paket($id_paket)
    {
        return $this->db->get_where('paket', array('id_paket' => $id_paket))->row_array();
    }

    /*
     * Get all paket
     */
    function get_all_paket($params = array())
    {
        $this->db->order_by('paket.id_paket', 'desc');
        $this->db->join('tbl_users', 'tbl_users.user_id=paket.created_by', 'left');
        $this->db->join('keberangkatan', 'keberangkatan.id_keberangkatan=paket.fk_id_keberangkatan', 'left');
        $this->db->where('paket.publish', 1);
        return $this->db->get('paket')->result_array();
    }
}
